FROM resin/rpi-raspbian
	
RUN curl -sL https://deb.nodesource.com/setup | sudo bash -


RUN apt-get update && apt-get install nodejs \
    git \
    npm

RUN ln -s /usr/bin/nodejs /usr/bin/node

RUN npm install -g forever \
    nodemon

COPY src/start.sh /
RUN chmod +x /start.sh

CMD ["/bin/bash", "-c", "/start.sh"]